name: Week3
version: 0.0.0

ghc-options: -Wall

dependencies:
 - base == 4.*
 - ilist
 - MissingH
 - safe
 - utility-ht

library:
  source-dirs: src

tests:
  spec:
    defaults: hspec/hspec@master
    dependencies: Week3
