name:                cis194-homework04
version:             0.1.0.0
github:              "githubuser/cis194-homework04"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2019 Author name here"

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/cis194-homework04#readme>

dependencies:
- base >= 4.7 && < 5
- primes

library:
  source-dirs: src

tests:
  cis194-homework04-test:
    main:                TestMain.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cis194-homework04
    - QuickCheck
    - hspec
    - primes
